### PR TITLE
Fixed bug in return value of handle_copy_private_file_from_local_folder.

### LINKED ISSUE #92: Function 'save_post_owners' doesn't seem to properly save the owners when called from cuar_create_private_file
This is the parameters array $files_to_move used to invoke cuar_bulk_create_private_files($files_to_move); 

https://www.dropbox.com/s/p2enyvto85j7lqq/Screenshot%202015-04-16%2022.06.26.png?dl=0

It makes the new post, and stepping through the code, it looks like things are going well, but the files never show up in the private file area, and the files are not moved into the target md5 directory.

I think that looks like the example you gave in the function doc header, but maybe I'm missing something simple?

Thanks,

S

### PR DESCRIPTION
**Pull request by ssteinerx**
Resolves #92.

### CODE REVIEW

**Comment by vpratfr** [comment]
Can you also fix $_POST issue as mentioned in #95 ?

**Comment by ssteinerx** [comment]
Will do.

**Comment by ssteinerx** [comment]
Done.

**Comment by ssteinerx** [comment]
Done.  Updated doc strings, tested, ready to merge (and please merge develop back into this branch if there's anything new there, too, please).

**Comment by vpratfr** [comment]
@ssteinerx I think you could implement #99 here. This is the same place and touches the same kind of functionnality.

**Pull request merged**
